#!/bin/sh

userresources=${XDG_CONFIG_HOME}/X11/Xresources
usermodmap=${XDG_CONFIG_HOME}/.config/X11/Xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

# merge in defaults and keymaps

if [ -f $sysresources ]; then
    xrdb -merge $sysresources
fi

if [ -f $sysmodmap ]; then
    xmodmap $sysmodmap
fi

if [ -f "$userresources" ]; then
    xrdb "$userresources"
fi

if [ -f "$usermodmap" ]; then
    xmodmap "$usermodmap"
fi

# start some nice programs
if [ -d /etc/X11/xinit/xinitrc.d ] ; then
 for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi

# Set the background color
xsetroot -solid "#2b303b"
# Start xautolock in the background with a 5 minute timer and i3lock
xautolock -time 5 -locker i3lock-pixelate.sh &
# Start i3wm
exec i3

