" Disable forced vi backwards compatibility
set nocompatible

" Change temp file locations
"" Directory in which to create backups
set backupdir=~/.vim/backup//
"" Directory in which to create swap files
set directory=~/.vim/swap//
"" Directory in which to create undo files
set undodir=~/.vim/undo//

" Character encoding
set fileencodings=utf-8

set backspace=indent,eol,start	" Allow backspacing over autoindent, line breaks and start of insert action
set showmatch	" Highlight matching {[(
set lazyredraw	" Redraw only when needed

" Don't beep
set visualbell
set noerrorbells

" Get out of insert mode faster
set notimeout
set ttimeout
set ttimeoutlen=50	" Key code delay

" Disable modeline for better security
set nomodeline

" Set 'Y' to only yank until end of line
nnoremap Y y$

" Colors
set t_Co=256	" Use 256 color mode
colors default	" Set the color theme to be used
if has('syntax') && !exists('g:syntax_on')
	syntax enable	" Enable syntax highlighting
endif

" Indentation settings
"" These may be further customized per filetype in vim/after/ftplugin/
setlocal tabstop=4			" Number of spaces vim expands existing \t to when editing
setlocal shiftwidth=4		"
setlocal softtabstop=4		" Number of spaces a tab counts for when editing
filetype indent plugin on	" Attempt to detect filetype/contents so that vim can autoindent etc
set autoindent				" When starting new line and no filetype-specific indenting is enabled, keep the same indent as the current line

" Display line numbers on the left
"" Hybrid line numbering
if exists('+relativenumber')
	set relativenumber
endif
"" Static line numbering
set number

" Searching
set nohls		" Disable highlighting
set ignorecase	" No case sensitivity when searching
set smartcase	" Case sensitive only when there is a captial letter in search
set incsearch	" Incrementally search while typing
set wrapscan	" Wrap to beginning of file if end is reached while searching
"" Center screen on match
nnoremap N Nzz
nnoremap n nzz

" Splitting
set splitright	" Horizontal split will go right
set splitbelow	" Vertical split will go below
"" Ctrl+J to go to split below current
nnoremap <C-J> <C-W><C-J>
"" Ctrl+K to go to split above current
nnoremap <C-K> <C-W><C-K>
"" Ctrl+L to go to split left of current
nnoremap <C-L> <C-W><C-L>
"" Ctrl+H to go to split right of current
nnoremap <C-H> <C-W><C-H>

" Folding
if has("folding")
	set foldenable			" Enable folding
	set foldnestmax=10		" Limit maximum embedded folds to 10
	set foldmethod=syntax	" Fold based on indent level
	"" space open/closes folds
	nnoremap <space> za
endif

" Set title to the name of the file
"" Reset the title to the buffer's full path every time a buffer is entered
auto BufEnter * :set title | let &titlestring = expand('%:p')

" File saving
"" Remove trailing whitespace on file save
autocmd BufWritePre * :%s/\s\+$//e
"" Allow saving of files as sudo when I forgot to start vim using sudo.
cmap w!! w !sudo tee > /dev/null %
"" Switch buffers without requiring that buffers be saved
set hidden
"" Save folds on exit
autocmd BufWinLeave *.* mkview
autocmd BufWinEnter *.* silent loadview
