" Character encoding
set fileencodings=utf-8

" Colors
set t_Co=256	" Use 256 color mode
colors default	" Set the color theme to be used
syntax enable	" Enable syntax highlighting

" Indentation settings
"" These are further customized per filetype in .vim/after/ftplugin/
setlocal tabstop=4		" Number of spaces vim expands existing \t to when editing
setlocal shiftwidth=4		"
setlocal softtabstop=4		" Number of spaces a tab counts for when editing
filetype indent plugin on	" Attempt to detect filetype/contents so that vim can autoindent etc
set autoindent			" When starting new line and no filetype-specific indenting is enabled, keep the same indent as the current line

" Display line numbers on the left
"" Hybrid line numbering
if exists('+relativenumber')
	set relativenumber
endif
set number

" Miscellaneous editor settings
set backspace=indent,eol,start	" Allow backspacing over autoindent, line breaks and start of insert action
set showmatch			" Highlight matching {[(
set nohls			" Disable highlighting
set lazyredraw			" Redraw only when needed
set incsearch			" Search as characters are typed

" Splitting
set splitright	" Horizontal split will go right
set splitbelow	" Vertical split will go below
"" Ctrl+J to go to split below current
nnoremap <C-J> <C-W><C-J>
"" Ctrl+K to go to split above current
nnoremap <C-K> <C-W><C-K>
"" Ctrl+L to go to split left of current
nnoremap <C-L> <C-W><C-L>
"" Ctrl+H to go to split right of current
nnoremap <C-H> <C-W><C-H>

" Folding
if has("folding")
	set foldenable		" Enable folding
	set foldnestmax=10	" Limit maximum embedded folds to 10
	set foldmethod=syntax	" Fold based on indent level
	" space open/closes folds
	nnoremap <space> za
endif

" Set title to the name of the file
autocmd BufEnter * let &titlestring = ' ' . expand("%:t")
set title

" File saving
"" Remove trailing whitespace on file save
autocmd BufWritePre * :%s/\s\+$//e
"" Allow saving of files as sudo when I forgot to start vim using sudo.
cmap w!! w !sudo tee > /dev/null %
"" Switch buffers without requiring that buffers be saved
set hidden
"" Save folds on exit
autocmd BufWinLeave *.* mkview
autocmd BufWinEnter *.* silent loadview
