# This is the main user configuration file
# It is sourced when zsh is started as an interactive shell

# Source file containing aliases;
source "${XDG_CONFIG_HOME}/zsh/aliases"
# Include ${HOME}/local/.bin in path if directory exists
if [ -d "${HOME}/.local/bin" ]; then
	export PATH="${PATH}:${HOME}/.local/bin"
fi

# Enable autocompletion
autoload -U compinit
compinit

# History settings
HISTFILE=~/.zsh_history
HISTSIZE=1000
SAVEHIST=1000
setopt appendhistory nomatch
## Ignore duplicate lines in the history
setopt HIST_IGNORE_DUPS
unsetopt autocd beep extendedglob notify

# Use vi mode
bindkey -v

# Automatically add ssh keys to the ssh-agent
## https://github.com/wwalker/ssh-find-agent
#. ssh-find-agent.sh
#ssh-find-agent -a
#if [ -z "$SSH_AUTH_SOCK" ]; then
#	eval $(ssh-agent) > /dev/null
#	ssh-add -l >/dev/null || alias ssh='ssh-add -l >/dev/null || ssh-add && unalias ssh; ssh'
#fi

# Set the left-aligned prompt to '#' if sudo, '%' otherwise
PS1="%# "

# Precommand - Runs for every new prompt
precmd() {
	if [ "${TERM}" = "screen" ]; then
		# Show current directory in right status of tmux
		tmux set -qg status-right "#{pane_current_path} "
	fi
}
